services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nexoura-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    # Automatically install dependencies on start to keep volumes in sync
    command: sh -c "npm install && npm run dev"
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: .
          target: /app
          action: sync
    restart: no
    # CRITICAL: change the restart policy to 'always' when deploying to production
    # restart: always

# Optional: Add a volume for node_modules to persist them and avoid re-installing
# however we are mounting the whole directory so we need to be careful with host vs container arch.
# The /app/node_modules volume in 'app' service handles this by making it an anonymous volume.
